version: '3'
services:
  md5breaker:
    container_name: md5breaker
    build: ../md5breaker
    ports:
    - "5000:5000"
    links:
    - redis
  redis:
    container_name: redis
    image: redis:latest
    ports:
    - "6379:6379"
  base64:
    container_name: base64
    build: ../baseEncodings/base64decoder
    ports:
     - "4000:4000"
  base32:
    container_name: base32
    build: ../baseEncodings/base32decoder
    ports:
     - "4001:4001"
  base16:
    container_name: base16
    build: ../baseEncodings/base16decoder
    ports:
     - "4002:4002"
  quokka-project:
    container_name: quokka-project
    build: .
    ports:
    - "5555:5555"
